// clientPhrases.js
// Microtextos cálidos por categoría.
// Consumo: window.ClientPhrases.get(category)

(function(){
  'use strict';
  window.ClientPhrases = (function(){
    const phrases = {
      calma: [
        "A veces la calma no llega corriendo.\nLlega despacio, casi tímida,\ncuando dejas de pelear con lo que sientes.\nRespira.\nLo estás haciendo mejor de lo que crees.",
    "Pon la mano en tu pecho.\nSiente cómo sube… y cómo baja.\nNo tienes que acelerar nada dentro de ti.\nAcompáñate un momento.\nTu cuerpo recuerda el camino.",
    "relaja la mandíbula.\nSuelta los hombros.\nAfloja un poco el mundo por dentro.\nLa calma es un acto de amor,\nno de control.",
    " no hace falta arreglarlo todo hoy.\nNi entenderlo.\nSolo necesitas un respiro consciente\npara recordar que aún tienes espacio\npara sentirte mejor.",
    "cuando todo parezca demasiado,\inhala contando hasta cuatro\ny exhala un poco más lento.\nAhí, en ese segundo extra,\nla calma empieza a abrir la puerta.",
    "permite que tu respiración haga por ti\nlo que tu cabeza no puede ahora mismo.\nNo pienses.\nSolo siente.\nLa calma empieza en el cuerpo.",
    "la paz llega vestida de silencio interno,\nde pausas pequeñas,\nde segundos que te das sin prisa.\nRegálate uno ahora.",
    "respira profundo, como abriendo una ventana\ndentro de tu pecho.\nLa tensión no se va de golpe,\npero cede cuando la miras con suavidad.",
    "imagina que el aire que entra\nes luz,\ny el que sale\nse lleva un poco de peso.\nHazlo dos veces más.\nNota la diferencia.",
    "hoy no tienes que ser fuerte.\nSolo presente.\nLa calma se acerca cuando sueltas\nla obligación de aparentar que estás bien.",
    "cierra los ojos un instante.\nEscucha el ritmo de tu respiración.\nTodo está más lento ahí dentro.\nEsa es la puerta que te devuelve la paz.",
    "Cuando sientas que no puedes más,\ndetente.\nRespira.\nTu alma también necesita descansar\nentre batalla y batalla.",
    "la calma no es ausencia de ruido,\nes poder escucharte a ti\npor encima de él.",
    "tu respiración nunca te abandona.\nEs tu amiga más constante.\nVuelve a ella cuando todo se tambalee.",
    "Permite que tu pecho se expanda.\nDeja que entre un poco más de aire.\nA veces la calma empieza\ncon un simple 'sí, puedo'.",
    "Tu mente corre rápido,\npero tu cuerpo puede enseñarle a frenar.\nRespira lento.\nMuy lento.\nY quédate ahí.",
    "No te exijas paz inmediata.\nLa calma también necesita tiempo\npara llegar y acomodarse en ti.",
    "No estás fallando por sentirte agitada.\nEstás agotada.\nY el agotamiento no se soluciona con fuerza,\nsino con compasión.",
    "Busca un rincón dentro de ti\nque aún esté tranquilo.\nAbrázalo.\nHazlo más grande con cada exhalación.",
    "La calma florece\ncuando dejas de pelear contigo misma.\nAcepta el instante como es.\nRespira desde ahí.",
    "Tu cuerpo guarda más sabiduría\nde la que crees.\nSi lo escuchas,\nél te dirá cuándo bajar el ritmo.",
    "Hoy no busques respuestas.\nBusca respiraciones.\nCada una te llevará un poquito\nmás cerca de tu centro.",
    "La calma aparece\ncuando entiendes que no tienes que huir\nde lo que sientes.",
    "Tu corazón late fuerte\nporque quiere sostenerte.\nAgradécele y respira más suave.\nÉl también se calmará.",
    "La calma es como el mar al amanecer:\nprimero tenue,\nluego profunda,\nsi la miras el tiempo suficiente.",
    "Permítete descansar sin justificarte.\nDescansar también es avanzar.",
    "Cada vez que suspiras,\ntu cuerpo suelta algo que ya no necesita.\nRespira más profundo.\nRegálate un poco más de espacio.",
    "Tu mente puede suspender el ruido\ncuando le hablas con dulzura.\nInténtalo:\n'No pasa nada, estoy aquí contigo.'",
    "Si hoy te tiemblan las ideas,\napoya la espalda,\nrespira hondo,\ny deja que sea el cuerpo quien te sostenga.",
    "La calma crece cuando la honras,\ncuando la cuidas,\ncuando la eliges\naunque el resto del mundo corra.",
    "Escucha el aire entrando por tu nariz.\nEscucha cómo sale.\nEsa música suave\nes tu alma volviendo a su hogar.",
    "Hoy puedes detener el mundo.\nSolo respira\ny observa cómo todo se acomoda dentro de ti.",
    "La calma no desaparece;\nsolo se esconde detrás\nde una respiración consciente.",
    "No apresures tu alivio.\nLa calma llega cuando tú\nte das un poco más de paciencia.",
    "Cierra los ojos.\nImagina que te abrazas desde dentro.\nQuédate ahí un instante.\nEso también es calma.",
    "Siente el peso de tu cuerpo.\nDéjalo caer un poco más.\nNo tienes que sostener nada\nen este momento.",
    "La mente grita,\npero el cuerpo susurra.\nElige al que habla más suave.",
    "La calma es un gesto interno,\nno una circunstancia externa.\nPuedes elegirlo ahora.",
    "No estás perdiendo el control.\nEstás aprendiendo a respirar\ndentro de tu mundo interno.",
    "El aire que entra te renueva.\nEl que sale te aligera.\nHazlo tres veces más.\nSiente cómo cambia algo en ti.",
    "La calma no es un destino,\nes un camino que recorres\nun respiro a la vez.",
    "Hoy no tienes que ser una versión brillante.\nSolo una versión presente.\nEso basta.",
    "A veces el miedo se calma\ncuando escucha tu respiración\nmás que tus pensamientos.",
    "No estás obligada a sentirte bien,\npero sí puedes darte permiso\npara sentirte un poco mejor.",
    "La calma te busca,\naunque tú no la sientas.\nDéjale una rendija abierta.",
    "Abrázate internamente\ncon cada respiración lenta.\nTu alma lo nota.\nTu cuerpo también.",
    "Permite que el mundo afuera siga su ritmo.\nEl tuyo puede ser otro.\nUno más suave.\nUno más tuyo.",
    "Cuando todo se desordena,\ntu respiración puede ser tu único orden.\nSostente en ella.",
    "La calma es un regalo\nque puedes darte incluso\nen medio del caos.",
    "Hoy siéntate contigo.\nRespira.\nY recuerda:\nlo que ahora pesa,\ntambién puede aliviarse."
      ],
      validacion: [
       "Lo que sientes es real.\nNo importa si alguien más no puede verlo.\nTu emoción tiene historia,\ntiene raíces,\ntiene derecho a existir.\nEscúchala un momento.",
    "No estás exagerando.\nEstás sintiendo.\nY sentir nunca es un error.\nPermítete validar tu propio corazón,\naunque el mundo no entienda su lenguaje.",
    "Tu dolor también merece un asiento.\nNo lo escondas para no incomodar.\nLo que se silencia pesa más.\nDale un lugar en tu pecho\nhasta que pueda descansar.",
    "Puedes estar rota y ser valiosa.\nPuedes estar cansada y seguir siendo fuerte.\nNo tienes que elegir un solo estado.\nEres compleja, humana\ny profundamente digna.",
    "No necesitas justificar tu tristeza.\nNo necesitas permiso para llorar.\nSentir no es debilidad:\nes honestidad contigo misma.",
    "Tu cuerpo habla con emociones.\nNo ignores ese idioma.\nLo que te duele está intentando decirte algo,\nno castigarte.",
    "Nadie más vive tu vida desde dentro.\nNo permitas que minimicen tu historia\nsolo porque no la comprenden.\nLa comprendes tú,\ny eso la valida.",
    "Está bien no estar bien.\nNo te convierte en un problema.\nTe convierte en un ser vivo,\nsensible\ny profundamente humano.",
    "Lo que hoy pesa, pesa de verdad.\nNo te inventas el cansancio.\nNo inventas el miedo.\nTu alma está pidiendo cuidado,\nno juicio.",
    "Mereces comprensión,\nespecialmente de ti misma.\nDarte validación interna\nes el primer paso para sanar.",
    "No eres demasiado emocional.\nEres profunda.\nTu sensibilidad es tu brújula,\nno una falla.\nAbrázala.",
    "No te digas 'no es para tanto'.\nSi tu corazón lo siente,\nes para tanto.\nTu verdad importa.",
    "Tus lágrimas cuentan verdades\nque tu voz no siempre sabe decir.\nEscúchalas.\nTambién son sabias.",
    "No eres un peso.\nEres una persona con historia.\nY esa historia merece respeto.",
    "A veces la emoción no se entiende,\nsolo se siente.\nY eso es válido.",
    "No tienes que justificar\npor qué algo te afecta.\nTe afecta\ny ese es argumento suficiente.",
    "Tu cansancio emocional\nno es flojera.\nEs señal de que has sostenido demasiado\npor demasiado tiempo.",
    "Lo que te dolió, te dolió.\nNo importa si otros lo minimizan.\nTu corazón merece ser honrado.",
    "Permítete estar triste\nsin tratar de esconderte.\nTu tristeza también merece luz.",
    "Tú también mereces ser cuidada\nen tus días grises.\nNo solo en los días buenos.",
    "Tu silencio también habla.\nA veces dice: 'Estoy cansada'.\nA veces: 'Necesito abrazo'.\nEscúchalo sin juzgarlo.",
    "El mundo te pide ser fuerte,\npero tu alma te pide ser honesta.\nElige tu alma.",
    "Tu vulnerabilidad no es un defecto.\nEs tu puerta a la verdad,\na la conexión,\na ti misma.",
    "Lo que te ocurre internamente\nno necesita validación externa\npara ser real.",
    "Estás sintiendo demasiado\nporque has aguantado demasiado.\nEso no te hace débil,\nte hace humana.",
    "No estás perdiendo el control.\nEstás escuchando emociones\nque llevaban tiempo esperando\ntu atención.",
    "Puedes llorar sin pedir perdón.\nPuedes sentir sin dar explicaciones.\nTu interior te pertenece.",
    "Tu historia emocional\nno se mide con lógica,\nsino con heridas.",
    "A veces amar implica romperse un poco.\nNo te juzgues por ello.\nEstabas intentando.\nY eso ya vale.",
    "Tus límites importan,\naunque otros no los respeten.\nRespétalos tú.",
    "No estás dramática:\nestás cargada.\nTu sistema nervioso\nestá pidiendo descanso,\nno crítica.",
    "Tus emociones no están equivocadas.\nSon respuestas a lo vivido.\nY todo lo vivido importa.",
    "La confusión también es válida.\nEl no saber también es válido.\nNo necesitas tener claridad inmediata.",
    "Lo que te duele\nno te convierte en menos.\nTe convierte en alguien\nque sintió intensamente.",
    "Tu corazón merece compasión,\nno juicio.\nDásela tú primero.",
    "Tus emociones no están en tu contra.\nEstán llamando a la puerta\npara decirte 'mírame'.",
    "La tristeza no es falla.\nEs información.\nEs señal.\nEs parte del camino.",
    "Lo que sientes no te hace difícil.\nTe hace auténtica.",
    "Puedes validar tu dolor\nsin convertirlo en tu identidad.\nSon cosas distintas.",
    "Tú importas incluso\ncuando no tienes energía\npara demostrarlo.",
    "Tu incomodidad interna\nes un mensaje, no una amenaza.\nEscúchalo con suavidad.",
    "No te castigues por sentir fuerte.\nSolo los que aman profundo\nsienten así.",
    "Tu emoción es legítima\naunque no puedas explicarla.\nNo todo lo real se explica.\nAlgunas cosas simplemente se sienten.",
    "Eres digna incluso en tu caos interno.\nLa dignidad no se pierde,\naunque la mente tiemble.",
    "Tú también mereces comprensión\nen momentos donde solo tienes lágrimas.\nEres valiosa ahí también.",
    "No es tu culpa sentir.\nNunca lo fue.\nTu corazón está hablando\nde lo que vivió.",
    "Lo que te cuesta\ntambién habla de tu profundidad.\nNo te disculpes\npor ser emocionalmente real.",
    "Cada emoción tuya\nes una pieza de una historia\nque merece ser honrada.",
    "No tienes que esconderte.\nTu vulnerabilidad también es belleza.",
    "Lo que sea que estás sintiendo ahora,\ndéjalo ser.\nTu emoción no es un enemigo,\nes una parte de ti\npidiendo un abrazo."
        
      ],
      motivacion: [
         "No necesitas cambiar tu vida hoy.\nSolo dar un paso pequeño,\nuno que te recuerde\nque sigues caminando.\nEl resto vendrá contigo.",
    "Has superado cosas\nque alguna vez juraste\nque no podrías atravesar.\nNo te subestimes:\nla fortaleza ya vive en ti.",
    "La motivación no siempre llega antes de actuar.\nA veces aparece después,\ncuando te ves capaz,\ncuando descubres que sí podías.",
    "Aunque avances lento,\nsigues avanzando.\nEso ya te convierte\nen alguien imparable.",
    "Tu futuro no necesita grandes saltos,\nsolo decisiones pequeñas, repetidas.\nEse es el secreto\nde quienes cambian su vida.",
    "No eres tu cansancio.\nNo eres tu miedo.\nEres la persona\nque sigue intentándolo.",
    "Lo que haces por ti hoy,\npor pequeño que sea,\ntu versión futura\nlo va a agradecer.",
    "Cada vez que eliges cuidarte,\nestás reescribiendo tu historia.\nEste momento también cuenta.",
    "La disciplina amable\ntransforma más que la exigencia dura.\nTrátate como tratarías\na alguien que amas.",
    "Si hoy no puedes con todo,\nelige una sola cosa.\nHazla con cariño.\nEso también es avanzar.",
    "Eres más fuerte\nde lo que los días difíciles\nte han hecho creer.\nRecupérate con suavidad,\npero recupérate.",
    "No todo progreso se nota por fuera.\nAlgunas de tus mayores victorias\nsolo tú las has visto.\nY aun así cuentan.",
    "Lo que te espera\nes más grande que lo que perdiste.\nTen fe en tu camino,\naunque hoy no lo veas claro.",
    "Vales más que tu productividad.\nMucho más.\nY cuando lo entiendes,\navanzas desde otro lugar.",
    "El mundo cambia\ncuando tú cambias un pensamiento.\nUno solo.\nHoy puede ser ese día.",
    "La duda aparece\ncuando estás a punto de crecer.\nTómala de la mano\ny sigue.",
    "Tu historia no está escrita del todo.\nCada respiración nueva\nes un capítulo posible.",
    "Hoy puedes elegirte a ti.\nY si lo haces hoy,\npuedes hacerlo mañana.\nY así se construye una vida.",
    "No necesitas ser perfecta\npara avanzar.\nSolo sincera contigo misma.",
    "Hazlo por la persona\nque soñaste ser cuando eras niña.\nElla aún te mira\ncon esperanza.",
    "Cada día que decides levantarte,\naunque no tengas fuerzas,\nestás ganándole a algo\nque quiso detenerte.\nEso es heroico.",
    "Lo que estás construyendo dentro de ti\nes más valioso\nque cualquier meta externa.\nNo te detengas ahora.",
    "No tienes que correr.\nPuedes avanzar despacio\nsiempre que avances\ndesde el corazón.",
    "Tu constancia silenciosa\nvale más que cualquier explosión de energía.\nSiéntete orgullosa\nde volver a intentarlo.",
    "Cree en la mujer\nque puedes llegar a ser.\nElla ya existe dentro de ti,\nesperando que la llames.",
    "Has sobrevivido tu peor día.\n¿Te das cuenta de lo grande que es eso?\nNo eres débil.\nEres resistente.",
    "Si el camino se hace cuesta arriba,\nno es señal de que no puedas,\nes señal de que estás creciendo.",
    "A veces la vida te pide\nsolo una cosa:\nque sigas.\nCon miedo, con dudas,\npero sigas.",
    "Lo que buscas fuera\nya está sembrado dentro.\nSolo necesitas regarlo\nun poco cada día.",
    "No importa cuántas veces caigas.\nImporta cuántas veces\ndecidas levantarte.\nTu alma sabe cómo hacerlo.",
    "Hoy puedes empezar de nuevo.\nSin culpa.\nSin explicación.\nSolo porque lo necesitas.",
    "No tengas miedo\nde convertirte en alguien mejor.\nNo pierdes nada:\nsolo ganas espacio para brillar.",
    "Hazlo aunque tiemble tu voz.\nHazlo aunque te tiemble el alma.\nEl valor no es ausencia de miedo,\nes seguir pese a él.",
    "Eres semilla y también flor.\nProceso y resultado.\nHonra cada fase.",
    "No estás tarde.\nNo estás atrasada.\nEstás justo en el minuto\nen el que tu vida puede girar.",
    "Cuando te canses,\ndescansa.\nPero no renuncies\na lo que tu corazón anhela.",
    "Dentro de ti hay una voz pequeña\nque siempre supo que podías.\nEscúchala hoy.",
    "Celebra las victorias mínimas.\nEllas también construyen confianza.",
    "A veces avanzar\nes simplemente no retroceder.\nEso también cuenta.",
    "El futuro te está esperando.\nDa un paso hacia él\ncon la suavidad que puedas.\nNada más.",
    "No importa cuán lento vayas.\nSigues siendo más rápida\nque quien no se atreve a empezar.",
    "Confía en tu ritmo.\nNo necesitas correr\npara llegar.",
    "Lo que hoy parece pequeño\nmañana será tu punto de apoyo.\nSigue sembrando.",
    "La vida te ha puesto obstáculos,\npero tú te has puesto de pie.\nEso es motivo\npara creer en ti.",
    "No necesitas motivación eterna.\nSolo necesitas volver a intentarlo\ncada vez que puedas.",
    "No estás sola en tu lucha.\nTu fuerza interior\ncamina contigo.",
    "Lo que te duele hoy\npuede ser la razón\npor la que mañana seas más fuerte.",
    "Hazlo por ti.\nPor la mujer que estás construyendo.\nPor la vida que mereces.",
    "Si hoy te sientes perdida,\nrecuerda esto:\nsolo se pierde quien deja de buscar.\nY tú sigues buscando.",
    "Cada nuevo amanecer\nes una invitación\na intentarlo de nuevo.\nAcepta la invitación.\nEl mundo aún no ha visto lo mejor de ti."
      ],
      anclaje: [
        "Vuelve a tu cuerpo.\nSiente tus manos.\nSiente tus pies.\nAquí, en este instante,\nla tormenta no puede tocarte.",
    "El presente es tu refugio.\nNo está en tu mente,\nestá en tu respiración.\nVuelve a ella como quien vuelve a casa.",
    "Toca algo real:\nla mesa, tu ropa, el suelo.\nEso es ahora.\nEso es verdad.\nQuédate ahí un momento.",
    "Inhala profundamente,\ncomo si te reunieras contigo.\nExhala lento,\ncomo si limpiaras espacio interno.\nYa estás volviendo.",
    "Tu mente viaja rápido,\npero tu cuerpo siempre está aquí.\nEscúchalo.\nEs tu ancla más fiel.",
    "Mira a tu alrededor.\nTres cosas que ves.\nDos que oyes.\nUna que sientes.\nYa regresaste.",
    "No estás en el ayer.\nNo estás en el mañana.\nEstás aquí.\nRespira.\nEso basta.",
    "Pon una mano en tu pecho\ny otra en tu abdomen.\nSiente el movimiento.\nEres real.\nEstás a salvo.",
    "Cuando la mente te arrastre,\npon los pies firmes en el suelo.\nEse contacto es tu puente\nde regreso a ti.",
    "Vuelve a ti con suavidad.\nEl presente no exige,\nsolo sostiene.",
    "Siente el aire entrando.\nSiente el aire saliendo.\nNada más.\nEso es anclaje:\nreconectar con lo simple.",
    "No busques respuestas ahora.\nBusca tu respiración.\nElla es suficiente\npara traerte de vuelta.",
    "Tu cuerpo sabe volver a la calma\nantes que tu mente.\nConfía en él.\nDéjale guiarte.",
    "Describe mentalmente\nalgo que puedas ver ahora mismo.\nEsa descripción te devuelve\nal instante presente.",
    "Tu respiración es tu cuerda\nen medio del caos.\nAgárrala.\nElla no se rompe.",
    "El presente es más ancho\nde lo que crees.\nHay espacio para ti aquí.",
    "Pon atención a tu postura.\nRelaja los hombros.\nAfloja la mandíbula.\nYa estás volviendo.",
    "Escucha un sonido cercano.\nEse sonido pertenece al ahora.\nY tú también.",
    "La mente se va lejos,\npero siempre puedes traerla\ncon una inhalación profunda.",
    "Cuando todo parezca confuso,\nencuentra algo físico que te sostenga.\nTu cuerpo conoce el camino de regreso.",
    "Mira tus manos.\nObsérvalas sin juzgar.\nEllas también cuentan tu historia.\nY te anclan al presente.",
    "Nombra en voz baja lo que sientes.\nPonerle nombre\nya es empezar a volver.",
    "Apoya la espalda.\nSiente el soporte.\nNo tienes que sostenerte sola\nen este segundo.",
    "Trae tu mente a tu cuerpo,\nno tu cuerpo a tu mente.\nAquí es donde respira la vida.",
    "Pon atención a un pequeño detalle\nde tu entorno.\nEse detalle es tu ancla temporal.",
    "Siente el peso de tu cuerpo\nsobre lo que te sostiene.\nNo tienes que sujetarlo todo tú.",
    "Pasa lentamente una mano\nsobre tu brazo.\nEse gesto te dice:\n“Estoy contigo”.",
    "No necesitas claridad para volver.\nSolo un respiro consciente\nque diga:\n“Aquí estoy”.",
    "Tu mundo interno se calma\ncuando tu cuerpo encuentra un punto firme.\nEse punto está más cerca\nde lo que crees.",
    "Cierra los ojos.\nNota la temperatura del aire.\nEse simple acto\nte devuelve al presente.",
    "El anclaje es recordar\nque tienes un cuerpo.\nY que ese cuerpo\nsabe cómo sostenerte.",
    "Cuando el miedo te saque del momento,\nvuelve a tus sentidos:\nvista, oído, tacto.\nEs tu triángulo de regreso.",
    "A veces solo necesitas tocar\nalgo real.\nLo real calma.",
    "Cuenta tus respiraciones\nhasta llegar a cinco.\nLuego empieza de nuevo.\nEso es volver.",
    "El presente siempre es más amable\nde lo que imaginas.\nAcércate a él despacio.",
    "Toma un objeto cercano.\nObsérvalo con detalle.\nLa atención plena\nes una cuerda de rescate.",
    "Siente el ritmo de tu corazón\nsin juzgarlo.\nEse ritmo\nes la prueba de que sigues aquí.",
    "No intentes controlar tu mente.\nSolo invita a tu cuerpo\na ocupar su espacio.",
    "Cada inhalación dice:\n“Estoy aquí”.\nCada exhalación dice:\n“Puedo con esto”.",
    "Si la cabeza te lleva lejos,\nel cuerpo te traerá de vuelta.\nConfía en él.",
    "Abre los ojos lentamente.\nMira un punto fijo.\nPermanece ahí unos segundos.\nEl presente te reconoce.",
    "Apoya los pies firmes en el suelo\ny respira.\nEsa postura\nes un puente hacia ti.",
    "No estás perdida.\nSolo estás fuera de tu cuerpo.\nVuelve.\nÉl siempre te recibe.",
    "El anclaje no siempre es inmediato,\npero siempre es posible.\nInsiste con suavidad.",
    "Haz una respiración profunda\ncomo si aspiraras calma\ndesde el suelo hasta tu pecho.",
    "Estás a salvo en este instante.\nRecuérdalo.\nSolo este instante importa.",
    "Cada respiración lenta\nte acerca un poco más\na la tierra firme dentro de ti.",
    "Tu cuerpo no te abandona.\nIncluso cuando la mente huye.\nÉl se queda.\nEs tu casa.",
    "Vuelve a lo que puedes tocar.\nVuelve a lo que puedes ver.\nLa realidad física\nes tu refugio.",
    "Estás aquí.\nRespirando.\nSosteniéndote.\nVolviendo a ti.\nY eso es suficiente."
      ],
      rutina: [
        "Hoy no tienes que lograr nada extraordinario.\nSolo cuidarte un poco.\nUn paso suave.\nUn gesto pequeño hacia ti.\nEso también es progreso.",
    "La rutina puede ser refugio\nsi la habitas con intención.\nHazlo despacio,\na tu ritmo,\ncomo quien vuelve a casa.",
    "Haz una cosa a la vez.\nY hazla como si mereciera\ntoda tu atención.\nEso es vivir con presencia.",
    "Beber agua,\nrespirar profundo,\nmover el cuerpo un poco.\nLos pequeños hábitos\nsostienen grandes vidas.",
    "Hoy elige lo esencial:\nuna pausa,\nun respiro,\nun momento para ti.\nLo demás puede esperar.",
    "Tu bienestar no depende\nde grandes esfuerzos,\nsino de pequeños actos\nque repites con cariño.",
    "La rutina no tiene que ser rígida.\nPuede ser suave,\ncomo una mano que guía\ny no que presiona.",
    "Empieza tu día\ncon un gesto amable hacia ti.\nEse gesto cambia el tono\nde todo lo que sigue.",
    "Sé constante contigo,\nno exigente.\nLa constancia suave\ntransforma más que la presión.",
    "Si hoy te sientes pesada,\nsimplifica.\nEnfócate en una sola cosa:\nestar contigo.",
    "Organiza tu día\ncomo quien acomoda flores.\nCon calma,\ncon intención,\nsin prisa.",
    "El equilibrio se construye\ncon hábitos pequeños.\nUno hoy,\notro mañana,\ny tu vida cambia.",
    "Descansa cuando lo necesites.\nNo hay rutina sana sin descanso.\nTu cuerpo te lo agradecerá.",
    "Respira antes de empezar.\nRespira mientras haces.\nRespira cuando termines.\nLa respiración también es rutina.",
    "No te presiones por hacer más.\nHaz lo que puedas\ncon amor.\nY eso será suficiente.",
    "Tu rutina no define tu valor,\npero puede cuidar tu energía\nsi la haces tuya.",
    "Elige un hábito pequeño\nque te acerque a tu bienestar.\nRepítelo hoy.\nY repítelo mañana.",
    "Tu autocuidado diario\nes una conversación silenciosa\ncon tu propia alma.",
    "Haz pausas pequeñas\npara volver a ti.\nLa pausa también es parte\nde la rutina.",
    "No necesitas despertar perfecta,\nsolo presente.\nLo demás se construye\na lo largo del día.",
    "Tu mañana no tiene que ser productiva,\nsolo amable.\nEsa amabilidad\nte sostiene más que cualquier logro.",
    "Hoy puedes hacer lo justo.\nNi más.\nNi menos.\nLo justo que tu cuerpo necesite.",
    "Cuida tu energía\ncomo cuidas algo frágil.\nCon suavidad.\nCon respeto.",
    "Lo que repites cada día\nes lo que te transforma.\nCuida tus repeticiones.",
    "Marca un ritmo suave,\nuno que puedas sostener,\nuno que no te lastime.\nEse es tu ritmo real.",
    "La rutina no es obligación,\nes contención.\nUn espacio donde puedes descansar\nen lo familiar.",
    "Haz pequeñas cosas\nque te hagan sentir bien.\nLo pequeño, repetido,\nes poderoso.",
    "Tu día puede ser ligero\nsi tú eliges ser ligera contigo.",
    "A veces basta con ordenar un rincón\npara ordenar un poco el alma.\nEmpieza por algo pequeño.",
    "Regálate tiempo para respirar,\npara no correr,\npara existir sin prisa.\nEso también es vida.",
    "Cada día es una oportunidad\npara empezar distinto.\nNo necesitas perfección,\nsolo intención.",
    "Haz tu rutina con cariño.\nAunque sea simple.\nEspecialmente si es simple.",
    "No fuerces el ritmo.\nElige la suavidad.\nLa suavidad también avanza.",
    "Celebra los hábitos que mantienes,\naunque sean minúsculos.\nSon semillas de bienestar.",
    "Tu rutina es tu refugio.\nHazla cálida.\nHazla tuya.\nHazla un lugar donde quieras volver.",
    "Respira profundo entre tareas.\nLa vida se vuelve más ligera\ncuando tú lo haces.",
    "Cuando te sientas dispersa,\nvuelve a un hábito sencillo.\nEse pequeño acto\nte traerá al presente.",
    "No subestimes el poder\nde un día tranquilo.\nLos días tranquilos curan.",
    "Anota una cosa que quieras hacer.\nSolo una.\nY hazla con presencia plena.\nEso basta.",
    "La rutina se vuelve bella\ncuando dejas de hacerla por obligación\ny la haces por amor propio.",
    "Rompe la rutina cuando te pese,\nabrázala cuando te sostenga.\nLa flexibilidad también es autocuidado.",
    "No necesitas ser constante con todo.\nSolo con aquello que te hace bien.",
    "Tu energía es valiosa.\nDistribúyela con conciencia.",
    "Un pequeño hábito\npuede ser tu ancla en días difíciles.\nCuídalo.",
    "Si te pierdes,\nvuelve a lo básico:\nrespirar, beber agua,\nsentirte viva.",
    "Tu rutina te cuida\ncuando tú la cuidas a ella.",
    "Hoy puedes hacer tu día\nun poco más ligero.\nElige algo que aliviar,\nalgo que soltar.",
    "Haz espacio en tu día\npara una pausa consciente.\nEse segundo puede cambiarlo todo.",
    "Tu mejor versión\nno aparece de golpe.\nSe construye con hábitos suaves,\ndía tras día.",
    "Hoy hazlo simple.\nHazlo lento.\nHazlo tuyo.\nY deja que la vida también respire contigo."
      ],
      profundo: [
            "Hay partes de ti\nque llevan años pidiendo ser escuchadas.\nSiéntate con ellas sin prisas.\nNo para arreglarlas,\nsino para abrazarlas.",
    "Sanar no siempre es bonito.\nA veces es llorar lo que no lloraste\ny admitir lo que siempre evitaste.\nPero después…\nviene la luz.",
    "Tu profundidad no es peligrosa.\nEs un territorio sagrado\ndonde guardas verdades\nque solo tú conoces.\nEntra con respeto.",
    "No huyas de lo que sientes.\nAhí están las pistas\npara encontrar la paz\nque tanto buscas.",
    "Cada herida que miras de frente\npierde un poco de su poder.\nTu valentía\nvale más de lo que imaginas.",
    "Hay cosas que duelen\nporque importan.\nPorque te formaron.\nPorque aún enseñan.\nEscúchalas con compasión.",
    "Tu historia merece ser contada\ncon tu voz real.\nSin filtros.\nSin vergüenza.\nSin pedir permiso.",
    "Tu sombra no es tu enemiga.\nEs una parte herida\nque espera tu mano\ndesde hace tiempo.",
    "El alma también se cansa.\nTambién necesita silencio,\nno solo explicaciones.\nAbrázala.",
    "En lo profundo de ti\nviven respuestas antiguas.\nNo las fuerces.\nVendrán cuando estés lista.",
    "Hay memorias que duelen\nporque aún no has terminado\nde despedirte de ellas.\nHazlo despacio.\nHazlo con ternura.",
    "La sanación no es línea recta.\nEs curva, espiral,\nida y vuelta.\nY aun así,\nes avance.",
    "Tu sensibilidad\nno es una fractura,\nes un canal.\nPor él pasa tu verdad.",
    "A veces crecer\nes dejar ir versiones de ti\nque ya no sostienen tu alma.",
    "En tu interior hay habitaciones\nque nunca has visitado.\nLlévate una vela.\nConócete de nuevo.",
    "Eres más profunda\nque lo que has vivido.\nEres más grande\nque lo que te hirió.",
    "Siente lo que tengas que sentir,\npero no te quedes atrapada ahí.\nEl dolor es un mensajero,\nno un hogar.",
    "Lo que no dijiste,\nlo que guardaste,\nlo que callaste…\ntodo quiere espacio\npara liberarse.",
    "A veces la vida te rompe\npara mostrarte\nla fuerza que tenías escondida.",
    "Tu alma sabe cuándo avanzar\ny cuándo detenerse.\nEscúchala antes que al ruido.",
    "En tus silencios\nhay mensajes que aún no lees.\nQuédate quieta un momento.\nEscucha.\nAlgo quiere contarte algo.",
    "Lo profundo asusta\nporque es verdadero.\nPero también libera\ncuando decides entrar.",
    "No temas sentir tanto.\nLa profundidad es el lugar\ndonde se gestan los cambios reales.",
    "Tu corazón también acumula invierno.\nPero recuerda:\nningún invierno\nha sido eterno.",
    "Llorar no te rompe.\nTe abre.\nTe vacía.\nTe prepara para lo nuevo.",
    "Lo que no entiendes hoy\nun día será claridad.\nConfía en tu proceso,\naunque ahora duela.",
    "Hay partes de ti\nque solo florecen\ncuando ya no las escondes.",
    "El alma no grita,\nsusurra.\nPor eso necesitas silencio\npara escucharla.",
    "Lo profundo no es oscuridad,\nes raíz.\nY las raíces\nsostienen toda tu vida.",
    "A veces lo más valiente\nes reconocer\nque algo te dolió más\nde lo que aceptabas.",
    "Lo que cargas en silencio\npesa el doble.\nDéjalo salir,\naunque sea de a poquito.",
    "No temas cuestionarte.\nEs señal de que estás creciendo\nen la dirección correcta.",
    "El alma también sabe renacer\ncuando algo dentro se apaga.\nDéjale tiempo.\nElla vuelve siempre.",
    "Cuando tocas fondo emocional,\ntambién tocas verdad.\nY desde la verdad\nsiempre se puede construir.",
    "No te avergüences\npor sentir hondo.\nAsí sienten las almas grandes.",
    "La herida no te define,\npero sí te enseñó.\nHonra su lección.",
    "Perdonarte a ti misma\nes una de las formas más profundas\nde libertad interna.",
    "Lo que niegas te controla.\nLo que miras\nte transforma.",
    "Hay conversaciones contigo\nque llevan años esperando.\nNo tengas miedo de tenerlas.",
    "La verdad duele,\npero también sana.\nY tú estás lista\npara ambas cosas.",
    "Dentro de ti vive una mujer\nque sobrevivió a todo.\nSiéntate con ella.\nEscucha su historia.\nAgradécele.",
    "Tu alma sabe cuándo liberar,\ncuándo sostener,\ny cuándo sanar en silencio.",
    "No estás rota.\nEstás reacomodando piezas\nque nadie más entendió\nque eran sagradas.",
    "A veces lo profundo es oscuro\nporque aún no encendiste tu luz.\nEnciéndela tú.\nNo esperes a nadie.",
    "Hay dolores que se transforman\nsolo cuando los reconoces sin miedo.",
    "Lo que viviste\nno te hizo menos.\nTe hizo más consciente.",
    "Sanar no es olvidar,\nes recordar sin que duela igual.",
    "Tu alma tiene una capacidad inmensa\nde reconstruirse.\nHa probado su fuerza muchas veces.\nEsta vez no será diferente.",
    "Lo profundo puede asustar,\npero también puede revelarte\nquién eres realmente.",
    "Cada vez que te escuchas\nsin juicio,\nsin prisa,\nsin miedo,\ntu alma da un paso hacia la libertad."
      ],
      crisis: [
        "Respira un momento.\nNo tienes que entender nada ahora.\nTu cuerpo está reaccionando,\nno estás en peligro.\nQuédate conmigo aquí,\nsolo un respiro a la vez.",
    "Lo que sientes es intenso,\npero no es eterno.\nTu corazón late fuerte\nporque quiere protegerte.\nVamos a bajar despacio, juntas.",
    "No estás fallando.\nEstás atravesando una ola emocional.\nY las olas, aunque golpeen,\nsiempre terminan por bajar.",
    "Pon una mano en tu pecho.\nSiente el calor.\nEso es tu cuerpo diciendo:\n“Estoy contigo”.\nNo estás sola en esta sensación.",
    "Tu respiración es tu refugio.\nInhala un poco más lento.\nExhala un poco más largo.\nNo hay prisa.\nTienes todo el tiempo del mundo.",
    "Sé que duele.\nSé que pesa.\nPero también sé\nque ya sobreviviste a momentos así antes.\nTu fortaleza está aquí, aunque tiemble.",
    "Ahora no tomes decisiones.\nSolo respira.\nLa claridad volverá\ncuando tu cuerpo se calme.",
    "Si sientes que te desbordas,\nvuelve a lo que puedes tocar:\nel suelo, tu ropa, tu mano.\nLo físico te devuelve al presente.",
    "Eres más fuerte\nde lo que esta emoción te hace creer.\nEstás sintiendo algo grande,\npero tú eres más grande.",
    "No exijas calma inmediata.\nExige compañía interna.\nDite a ti misma:\n“Estoy aquí contigo\naunque tiemble”.",
    "Tu mente está acelerada,\npero tú puedes bajar el ritmo.\nHaz una exhalación larga,\ncomo si soltaras un peso.\nEso, así.",
    "El miedo se siente real,\npero no siempre dice la verdad.\nRespira y déjale pasar\ncomo una nube cargada.",
    "Tu cuerpo está en modo alerta,\npero ahora estás a salvo.\nRecuérdaselo con cariño,\nno con exigencia.",
    "Apoya bien los pies.\nSiente el suelo.\nEsa estabilidad también es tuya.\nRespira hacia ella.",
    "No tienes que controlar la ola,\nsolo dejar que pase\nmientras te sostienes un poco más.",
    "Lo estás haciendo bien.\nIncluso si lloras,\nincluso si tiemblas,\nincluso si te cuesta respirar.\nSigues aquí.\nEso ya es mucho.",
    "Abraza tu cuerpo\naunque no entiendas lo que sientes.\nTu cuerpo entiende más\nde lo que parece.",
    "Cuando la emoción suba,\nbaja tu velocidad.\nEn todo: en pensar,\nen respirar,\nen moverte.",
    "No te juzgues.\nNo te compares.\nNo te castigues.\nEstás navegando algo difícil.\nSé suave contigo.",
    "Mira un punto fijo.\nRespira hacia ese punto.\nComo si te ayudara a mantenerte.\nEstoy contigo.",
    "Si sientes presión en el pecho,\nes tu sistema nervioso pidiendo pausa.\nDásela.\nRespira un poco más hondo.\nExhala un poco más lento.",
    "Esto pasará.\nNo porque te lo diga yo,\nsino porque así funciona el cuerpo:\nnada intenso dura para siempre.",
    "Estás segura.\nEstás aquí.\nEstás respirando.\nY eso es suficiente por ahora.",
    "Tu dolor no es una amenaza,\nes un mensaje.\nLo escucharemos después.\nAhora, solo respira.",
    "Si sientes que te pierdes,\ntoca algo frío.\nEse contraste\nayuda a tu cuerpo a volver.",
    "No puedes controlar la emoción,\npero sí puedes controlar\ncómo respiras.\nEmpieza por ahí.",
    "Lo que sientes no te define.\nEs solo un estado.\nY los estados cambian.",
    "Coloca tu espalda contra algo.\nSiente el soporte.\nNo tienes que sostenerte sola ahora.",
    "Cuando la cabeza grite,\nvuelve al cuerpo.\nEl cuerpo sabe regresar al centro.",
    "Tu corazón late fuerte,\npero no está fallando.\nEstá respondiendo.\nRespira con él\nhasta que se calme.",
    "Tómate de la mano, literal.\nApriétala un poquito.\nEse contacto es un ancla\ny una promesa:\n“No me dejo sola”.",
    "Estás sintiendo demasiado a la vez.\nVamos a dividirlo:\nrespira.\nSolo respira.\nLo demás se ordena después.",
    "El miedo es ruido.\nTu respiración es música.\nElige qué escuchar ahora.",
    "No busques resolver nada.\nNo busques entender nada.\nSolo quédate aquí,\nconmigo,\nrespirando.",
    "Si la mente corre,\nno corras detrás de ella.\nDéjala ir.\nTu cuerpo te traerá de vuelta.",
    "No haces nada mal.\nNo eres un problema.\nEstás teniendo un momento difícil.\nY eso también es humano.",
    "Si el llanto llega,\ndéjalo.\nEl llanto es el cuerpo diciendo:\n“estoy liberando”.",
    "Cuenta tus respiraciones:\nuno inhalo,\ndos exhalo.\nHazlo cinco veces.\nSolo eso.",
    "Sé que asusta.\nSé que aprieta.\nPero también sé que pasará.\nQuédate conmigo hasta que empiece a soltar.",
    "Apoya una mano en tu abdomen.\nSiente cómo sube.\nSiente cómo baja.\nTu cuerpo está tratando de ayudarte.",
    "No huyas de este instante.\nNo hay amenaza.\nHay intensidad.\nY la intensidad baja\ncuando la miras sin miedo.",
    "Si te tiemblan las manos,\nes tu cuerpo liberando.\nDéjalo hacer.\nRespira a través de ello.",
    "Tu mente cree que no puedes.\nTu respiración sabe que sí.\nConfía en la respiración.",
    "Si sientes presión,\npon tus dos manos sobre tu pecho\ny presiona suave.\nEse gesto te contiene.",
    "No estás sola en tu dolor.\nEste momento pasa.\nRespira conmigo\nhasta que empiece a soltar.",
    "Toca tus piernas.\nSiente su forma.\nSiente su calor.\nTu cuerpo está aquí\ny te está trayendo de vuelta.",
    "No te pidas calma.\nPídete compañía.\nLa calma llega después.",
    "Si la cabeza te dice “no puedo”,\nel cuerpo susurra “inténtalo conmigo”.\nEscucha al cuerpo.",
    "Todo lo que sientes\nestá pasando dentro de ti,\npero no eres ese caos.\nSigues siendo tú.\nMás fuerte de lo que crees.",
    "Estoy contigo.\nRespiremos juntas.\nAunque duela.\nAunque asuste.\nRespiremos hasta que baje la ola."
      ]
    };

    function get(category) {
      if (!category || !phrases[category]) return [];
      return phrases[category].slice(0);
    }

    function random(category) {
      const arr = get(category);
      if (!arr.length) return null;
      return arr[Math.floor(Math.random()*arr.length)];
    }

    return {
      get,
      random
    };
  })();
})();
